// Code generated by hertz generator.

package hello

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return nil
	//// your code...
	//handlers := []app.HandlerFunc{
	//	func(c context.Context, ctx *app.RequestContext) {
	//		ctx.Set("zp", "handsome")
	//		//ctx.Next(c)
	//		ctx.Abort()
	//	},
	//}
	//return handlers
}

func _helloMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hello0Mw() []app.HandlerFunc {
	return nil
	// your code...
	//handlers := []app.HandlerFunc{
	//	func(c context.Context, ctx *app.RequestContext) {
	//		ctx.Set("zp", "good")
	//		//ctx.Abort()
	//	},
	//}
	//return handlers
}

func _shitMw() []app.HandlerFunc {
	// your code...
	return nil
}
