// Code generated by hertz generator.

package hello

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	hello "gpt/biz/model/hello"
)

// Shit .
// @router /hello/shit [GET]
func Shit(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello.HelloResp)
	if req.Name == "ysd" {
		resp.RespBody = "love"
	}
	c.JSON(consts.StatusOK, resp)
}
